# Generated by Django 2.2 on 2020-12-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=''),
        ),
    ]
